name: Deploy to GitHub Pages

on:
  # Déclenchez le workflow chaque fois que vous poussez vers la branche `main`
  # Vous utilisez un nom de branche différent ? Remplacez `main` par le nom de votre branche
  push:
    branches: [ master ]
  # Vous permet d'exécuter ce workflow manuellement à partir de l'onglet Actions sur GitHub.
  workflow_dispatch:

# Autoriser cette tâche à cloner le dépôt et à créer un déploiement de page
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 16
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
          package-manager: yarn


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master 
